### ISSUE TITLE
Carriage return in properties should not be interpreted

### ISSUE THREAD

**Issue by treziac** [Landoop/kafka-connect-ui#24]
In some case, when creating  new connector from editor and copy/pasting from windows notepad(or whatever tools which will convert new lines as \r\n), the curl command will contains \r in properties values

For example, by just copy/pasting the default file configuration, we get the following config
```
name=file-connector2
topic=mobile.services.catalog.enteruniverse
tasks.max=1
file=/var/log/ansible-confluent/connect.log
connector.class=org.apache.kafka.connect.file.FileStreamSourceConnector
```
which converts to
```
cat << EOF > file-connector
.json
{
  "name": "file-connector\r",
  "config": {
    "topic": "kafka-connect-logs\r",
    "tasks.max": "1\r",
    "file": "/var/log/ansible-confluent/connect.log\r",
    "connector.class": "org.apache.kafka.connect.file.FileStreamSourceConnector"
  }
}
EOF
curl -X POST -H "Content-Type: application/json" -H "Accept: application/json" -d @file-connector
.json /api/kafka-connect/connectors 
```

Which will create an exception on kafka-connect
```
[2017-03-01 17:33:06,858] ERROR Failed to reconfigure connector's tasks, retrying after backoff: (org.apache.kafka.connect.runtime.distributed.DistributedHerder)
org.apache.kafka.connect.runtime.rest.errors.ConnectRestException: IO Error trying to forward REST request: No content to map due to end-of-input
 at [Source: UNKNOWN; line: 1, column: 1]
        at org.apache.kafka.connect.runtime.rest.RestServer.httpRequest(RestServer.java:242)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$12.run(DistributedHerder.java:864)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: UNKNOWN; line: 1, column: 1]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3609)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3549)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2650)
```

Then i assume there is a kafka connect bug, because connector is created (in connect-configs topic) but not visible from api, and if i create a connector without carriage return, then the connector is duplicated in rest api (will try to get a consistent reproductible case to submit to kafka guys)

Disregarding kafka connect bug, the editor should automatically remove \r (or propose to remove it)

**Comment by Antwnis** [comment]
Closing as a fix has addressed this in the latest release 0.9.0
Please re-open if it's not fixed for you, cheers for the bug report !
